name: "cargo-assist"
author: "Marco Ieni"
description: "GitHub action to automatically format your Rust code"
inputs:
  clippy:
    description: >
      Whether to run `cargo clippy --fix` or not.
      Useful if you want to run only `cargo fmt`.
      Possible values: `true`, `false`.
      Default: `true`.
    default: true
    required: false
  clippy_allow_dirty:
    description: >
      Whether to add `--allow-dirty` to clippy or not.
      Useful if you want to run `cargo clippy --fix` on a dirty repository.
      If you run commands before cargo-assist, the repository might be dirty.
      Possible values: `true`, `false`.
      Default: `false`.
    default: false
    required: false
  clippy_flags:
    description: >
      Flags to pass to `cargo clippy --fix`.
      Default: `--all-targets --all-features --workspace`.
    default: "--all-targets --all-features --workspace"
    required: false
  commit_message:
    description: >
      Commit message to use when committing the changes.
      Default: `chore: format, fix lints`.
    default: "chore: format, fix lints"
    required: false
  fmt:
    description: >
      Whether to run `cargo fmt` or not.
      Useful if you want to run only `cargo clippy --fix`.
      Possible values: `true`, `false`.
      Default: `true`.
    default: true
    required: false
  github_token:
    description: >
      GitHub token of the author of the commit.
      If you provide `${{ secrets.GITHUB_TOKEN }}`,
      the author of the commit is the github-actions bot.
    required: true
  working_directory:
    description: >
      Directory where to run the commands.
      Defaults to repository's root.
      Useful if your rust project is in a subdirectory.
    required: false
branding:
  icon: "zap"
  color: "yellow"
runs:
  using: "composite"
  steps:
    - name: Configure git user from GitHub token
      uses: MarcoIeni/git-config@v0.1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: Run cargo-assist
      shell: bash
      run: |
        if [[ -n "${{ inputs.working_directory }}" ]]
        then
            cd "${{ inputs.working_directory }}"
        fi

        if [[ "${{ inputs.clippy_allow_dirty }}" == true ]]
        then
            CLIPPY_ALLOW_DIRTY="--allow-dirty"
        else
            CLIPPY_ALLOW_DIRTY=""
        fi

        CLIPPY_COMMAND="cargo clippy ${{ inputs.clippy_flags }} $CLIPPY_ALLOW_DIRTY --fix"

        if [[ "${{ inputs.clippy }}" == true ]]
        then
            echo "running `$CLIPPY_COMMAND`"
            $CLIPPY_COMMAND
        fi

        # If repository has uncommitted changes, it means that clippy fixed some lints
        if [[ -n $(git status -s) ]]
        then
            echo "fixed clippy lints"
            CLIPPY_FIXED=true
        else
            CLIPPY_FIXED=false
        fi

        if [[ "${{ inputs.fmt }}" == true ]]
        then
            echo "running cargo fmt"
            cargo fmt --all
        fi

        if [[ "${{ inputs.commit_message }}" == "chore: format, fix lints" ]]
        then
            echo "user didn't specify a custom commit message"
            COMMIT_MSG="chore: "

            if [[ "${{ inputs.fmt }}" == true ]]
            then
                COMMIT_MSG="${COMMIT_MSG}format"
                if [[ "${CLIPPY_FIXED}" == true ]]
                then
                    COMMIT_MSG="${COMMIT_MSG}, "
                fi
            fi

            if [[ "${CLIPPY_FIXED}" == true ]]
            then
                COMMIT_MSG="${COMMIT_MSG}fix lints"
            fi
        else
            echo "using custom commit message"
            COMMIT_MSG="${{ inputs.commit_message }}"
        fi

        # If repository has uncommitted changes, commit them
        if [[ -n $(git status -s) ]]
        then
            git add .
            git commit -m "$COMMIT_MSG"
            git push
        fi
