name: Test

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create test project
        run: |
          cargo new assist-test
          cd assist-test
          # Generate `Cargo.lock` file and `target` directory
          cargo check
          git init
          echo "target" > .gitignore
          git config --global user.email "test@example.com"
          git config --global user.name "Test"
          git add .
          git commit -m "first commit"
      - name: Run cargo-assist
        uses: ./ # Uses an action in the root directory
        with:
          working_directory: ./assist-test
          github_token: ${{ secrets.GITHUB_TOKEN }}
